name: Deploy to Jenkins

on:
  push:
    branches:
      - master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Frontend Deployment
        run: |
         curl -X GET "https://${{ secrets.JENKINS_URL }}/job/deploy-react/build?token=deploy123" \
                  --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
      - name: Trigger Jenkins Backend Deployment
        run: |
         curl -X GET "https://${{ secrets.JENKINS_URL }}/job/deploy-backend/build?token=deploybackend" \
                  --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
      
